version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .envDocker
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run docker:run
    depends_on:
      - postgres
    restart:
      always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .envDocker
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: